# Generated by Django 3.2.16 on 2024-03-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
